openapi: 3.0.0
info:
  title: SMUR Boilerplate API
  version: 1.0.0
paths:
  /user/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: "User created"
        "400":
          description: "User Not created"

  /user/login:
    post:
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: "Login successful"
        "400":
          description: "Login Failed"

  /user/profile:
    get:
      summary: Get user profile
      description: Returns authenticated user's profile
      security:
        - bearerAuth: []
      responses:
        "200":
          description: User profile fetched
        "500":
          description: Unauthorized

  /user/image:
    post:
      summary: Upload an image
      description: Uploads a single image file (handled by multer)
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
              properties:
                file:
                  type: string
                  format: binary
                  description: Image file to upload
      responses:
        "200":
          description: File uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: File uploaded successfully
                  filename:
                    type: string
                  path:
                    type: string
        "400":
          description: No file uploaded or invalid file
